# Generated by Django 4.2.5 on 2023-09-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_comission_day_of_week"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comission",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("1", "Domingo"),
                    ("2", "Segunda-feira"),
                    ("3", "Terça-feira"),
                    ("4", "Quarta-feira"),
                    ("5", "Quinta-feira"),
                    ("6", "Sexta-feira"),
                    ("7", "Sábado"),
                ],
                max_length=10,
                verbose_name="Dia da semana",
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="invoice",
            field=models.CharField(
                max_length=122, unique=True, verbose_name="Número nota fiscal"
            ),
        ),
    ]
